### ISSUE TITLE
Maven提交公库流程

### ISSUE THREAD

**Issue by destinyd** [mindpin/tech-exp#28]
具体请参照[Sonatype Guide](https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide)

中文可以参照[此文](http://www.trinea.cn/dev-tools/upload-java-jar-or-android-aar-to-maven-center-repository/)

我在此列出主要步骤，以及注意事项
#1 确认项目已经没有问题

最简单的测试方法为

```
mvn clean install
```

能正常安装，不报错
#2 注册sonatype(已经注册可以跳过)

注意：FullName 记得用英文名格式，前后分开，如Levi Chan
#3 首次Release可以[创建Ticket](https://issues.sonatype.org/secure/CreateIssue.jspa?issuetype=21&pid=10134)，寻求帮助
#4 生成数字签名

请参照Guide 第5条，以及[How To Generate PGP Signatures With Maven](https://docs.sonatype.org/display/Repository/How+To+Generate+PGP+Signatures+With+Maven)

数字签名必须上传公匙到公库
gpg --keyserver hkp://pool.sks-keyservers.net --send-keys yourpassphrase
#5 在pom里添加sonatype必填项目

参照Guide第6、7a.1条

注意<repositories>项可以不填，但是记得要设置~/.m2/settings.xml

```
<settings>
  ...
  <servers>
    <server>
      <id>sonatype-nexus-snapshots</id>
      <username>your-jira-id</username>
      <password>your-jira-pwd</password>
    </server>
    <server>
      <id>sonatype-nexus-staging</id>
      <username>your-jira-id</username>
      <password>your-jira-pwd</password>
    </server>
  </servers>
  ...
</settings>
```

将your-jira-id替换你sonatype的帐号，your-jira-pwd替换为密码
#6 发布快照(Publish Snapshots)

当项目配置完毕后执行

```
mvn clean deploy
```

如果没有报错，项目快照则会提交到[sonatype](https://oss.sonatype.org)，你可以在Repositories的snapshots里面找到你的项目，登录后你可以进行相应操作(删除)
#7 Release
## 7.1 提交stage版本

执行

```
mvn release:clean
mvn release:prepare
mvn release:perform -Darguments=-Dgpg.passphrase=PASSPHRASE
```

PASSPHRASE替换为你的签名ID
### 7.2.2 在Staging Repositories中找到自己的Repository（一般为artifactId-1000）

![- 20140604 - 124614](https://cloud.githubusercontent.com/assets/68806/3169701/f4e5f5a6-eba3-11e3-847f-5783f4b8ea4f.png)
### 7.2.3 选择close

注意：选择close之后系统会进行处理，需要及分钟才能看到结果，你可以刷新在Activity查看close的处理结果，以及各种错误信息
### 7.2.4 选择release

注意：当close处理完并且无错时，可以选择release选项进行发布
#8 在issue中comment
## 注意：

当release之后在search.maven.org中还不能马上搜索到，有时候可能是人员操作的原因，需要人工处理，根据具体情况回复，使之尽快传上公库。

**Comment by ben7th** [comment]
GOOD

**Comment by destinyd** [comment]
已转[knowledge-camp wiki](https://github.com/mindpin/knowledge-camp/wiki/Maven%E6%8F%90%E4%BA%A4%E5%88%B0%E4%B8%AD%E5%A4%AE%E5%BA%93%E7%9A%84%E6%B5%81%E7%A8%8B)
